apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.service.app}}
  name: {{.Values.service.name}}
spec:
  type: "{{.Values.service.type}}"
  ports:
    - name: http
      port: {{.Values.service.serviceport}}
      protocol: TCP
      targetPort: http
  selector:
    app: {{.Values.service.app}}
