{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nginxactivity.serviceAccountName" . }}
  labels:
{{ include "nginxactivity.labels" . | indent 4 }}
{{- end -}}
